#############################################################################
# Makefile for building: test.app/Contents/MacOS/test
# Generated by qmake (3.1) (Qt 6.4.0)
# Project:  ../test/test.pro
# Template: app
# Command: /Users/aleks/Qt/6.4.0/macos/bin/qmake -o Makefile ../test/test.pro -spec macx-clang CONFIG+=qtquickcompiler
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_CHARTS_LIB -DQT_OPENGLWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_QMLINTEGRATION_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacosx-version-min=10.14 -Wall -Wextra $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacosx-version-min=10.14 -Wall -Wextra $(DEFINES)
INCPATH       = -I../test -I. -I../../6.4.0/macos/lib/QtCharts.framework/Headers -I../../6.4.0/macos/lib/QtOpenGLWidgets.framework/Headers -I../../6.4.0/macos/lib/QtWidgets.framework/Headers -I../../6.4.0/macos/lib/QtOpenGL.framework/Headers -I../../6.4.0/macos/lib/QtGui.framework/Headers -I../../6.4.0/macos/lib/QtQml.framework/Headers -I../../6.4.0/macos/include -I../../6.4.0/macos/include/QtQmlIntegration -I../../6.4.0/macos/lib/QtNetwork.framework/Headers -I../../6.4.0/macos/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../6.4.0/macos/mkspecs/macx-clang -F/Users/aleks/Qt/6.4.0/macos/lib
QMAKE         = /Users/aleks/Qt/6.4.0/macos/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/aleks/Qt/6.4.0/macos/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/aleks/Qt/6.4.0/macos/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = test1.0.0
DISTDIR = /Users/aleks/Qt/Project/build-test-Qt_6_4_0_for_macOS-Release/.tmp/test1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacosx-version-min=10.14 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/aleks/Qt/6.4.0/macos/lib
LIBS          = $(SUBLIBS) -F/Users/aleks/Qt/6.4.0/macos/lib -framework QtCharts -framework QtOpenGLWidgets -framework QtWidgets -framework QtOpenGL -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtQml -framework QtNetwork -framework QtCore -framework IOKit -framework DiskArbitration -framework AGL -framework OpenGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../test/charts.cpp \
		../test/main.cpp \
		../test/mainwindow.cpp moc_charts.cpp \
		moc_mainwindow.cpp
OBJECTS       = charts.o \
		main.o \
		mainwindow.o \
		moc_charts.o \
		moc_mainwindow.o
DIST          = ../../6.4.0/macos/mkspecs/features/spec_pre.prf \
		../../6.4.0/macos/mkspecs/features/device_config.prf \
		../../6.4.0/macos/mkspecs/common/unix.conf \
		../../6.4.0/macos/mkspecs/common/mac.conf \
		../../6.4.0/macos/mkspecs/common/macx.conf \
		../../6.4.0/macos/mkspecs/common/sanitize.conf \
		../../6.4.0/macos/mkspecs/common/gcc-base.conf \
		../../6.4.0/macos/mkspecs/common/gcc-base-mac.conf \
		../../6.4.0/macos/mkspecs/common/clang.conf \
		../../6.4.0/macos/mkspecs/common/clang-mac.conf \
		../../6.4.0/macos/mkspecs/qconfig.pri \
		../../6.4.0/macos/mkspecs/modules/qt_ext_freetype.pri \
		../../6.4.0/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		../../6.4.0/macos/mkspecs/modules/qt_ext_libpng.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_charts.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_charts_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_chartsqml.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_chartsqml_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_core.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_core_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_dbus.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_designer.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_gui.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_help.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_help_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_linguist.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_network.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_network_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_opengl.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_png_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_qml.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quick.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quicktimeline.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_repparser.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_repparser_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_sql.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_svg.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_testlib.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_uitools.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_widgets.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_xml.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../../6.4.0/macos/mkspecs/features/qt_functions.prf \
		../../6.4.0/macos/mkspecs/features/qt_config.prf \
		../../6.4.0/macos/mkspecs/macx-clang/qmake.conf \
		../../6.4.0/macos/mkspecs/features/spec_post.prf \
		../test/.qmake.stash \
		../../6.4.0/macos/mkspecs/features/exclusive_builds.prf \
		../../6.4.0/macos/mkspecs/features/mac/sdk.prf \
		../../6.4.0/macos/mkspecs/features/toolchain.prf \
		../../6.4.0/macos/mkspecs/features/mac/toolchain.prf \
		../../6.4.0/macos/mkspecs/features/default_pre.prf \
		../../6.4.0/macos/mkspecs/features/mac/default_pre.prf \
		../../6.4.0/macos/mkspecs/features/resolve_config.prf \
		../../6.4.0/macos/mkspecs/features/default_post.prf \
		../../6.4.0/macos/mkspecs/features/mac/default_post.prf \
		../../6.4.0/macos/mkspecs/features/mac/objective_c.prf \
		../../6.4.0/macos/mkspecs/features/resources_functions.prf \
		../../6.4.0/macos/mkspecs/features/qtquickcompiler.prf \
		../../6.4.0/macos/mkspecs/features/mac/mac.prf \
		../../6.4.0/macos/mkspecs/features/warn_on.prf \
		../../6.4.0/macos/mkspecs/features/qt.prf \
		../../6.4.0/macos/mkspecs/features/resources.prf \
		../../6.4.0/macos/mkspecs/features/moc.prf \
		../../6.4.0/macos/mkspecs/features/unix/opengl.prf \
		../../6.4.0/macos/mkspecs/features/uic.prf \
		../../6.4.0/macos/mkspecs/features/unix/thread.prf \
		../../6.4.0/macos/mkspecs/features/qmake_use.prf \
		../../6.4.0/macos/mkspecs/features/file_copies.prf \
		../../6.4.0/macos/mkspecs/features/mac/rez.prf \
		../../6.4.0/macos/mkspecs/features/mac/asset_catalogs.prf \
		../../6.4.0/macos/mkspecs/features/testcase_targets.prf \
		../../6.4.0/macos/mkspecs/features/exceptions.prf \
		../../6.4.0/macos/mkspecs/features/yacc.prf \
		../../6.4.0/macos/mkspecs/features/lex.prf \
		../test/test.pro ../test/charts.h \
		../test/mainwindow.h \
		../test/parser.h ../test/charts.cpp \
		../test/main.cpp \
		../test/mainwindow.cpp
QMAKE_TARGET  = test
DESTDIR       = 
TARGET        = test.app/Contents/MacOS/test

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 12.3
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT__QMAKE_STASH_ = /Users/aleks/Qt/Project/build-test-Qt_6_4_0_for_macOS-Release/.qmake.stash
EXPORT_VALID_ARCHS = x86_64 arm64
EXPORT_DEFAULT_ARCHS = arm64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/aleks/Qt/Project/test/test.pro


include /Users/aleks/Qt/6.4.0/macos/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

test.app/Contents/MacOS/test: ui_charts.h ui_mainwindow.h $(OBJECTS)  
	@test -d test.app/Contents/MacOS/ || mkdir -p test.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../test/test.pro ../../6.4.0/macos/mkspecs/macx-clang/qmake.conf ../../6.4.0/macos/mkspecs/features/spec_pre.prf \
		../../6.4.0/macos/mkspecs/features/device_config.prf \
		../../6.4.0/macos/mkspecs/common/unix.conf \
		../../6.4.0/macos/mkspecs/common/mac.conf \
		../../6.4.0/macos/mkspecs/common/macx.conf \
		../../6.4.0/macos/mkspecs/common/sanitize.conf \
		../../6.4.0/macos/mkspecs/common/gcc-base.conf \
		../../6.4.0/macos/mkspecs/common/gcc-base-mac.conf \
		../../6.4.0/macos/mkspecs/common/clang.conf \
		../../6.4.0/macos/mkspecs/common/clang-mac.conf \
		../../6.4.0/macos/mkspecs/qconfig.pri \
		../../6.4.0/macos/mkspecs/modules/qt_ext_freetype.pri \
		../../6.4.0/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		../../6.4.0/macos/mkspecs/modules/qt_ext_libpng.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_charts.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_charts_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_chartsqml.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_chartsqml_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_core.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_core_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_dbus.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_designer.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_gui.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_help.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_help_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_linguist.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_network.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_network_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_opengl.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_png_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_qml.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quick.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quicktimeline.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_repparser.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_repparser_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_sql.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_svg.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_testlib.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_uitools.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_widgets.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_xml.pri \
		../../6.4.0/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../../6.4.0/macos/mkspecs/features/qt_functions.prf \
		../../6.4.0/macos/mkspecs/features/qt_config.prf \
		../../6.4.0/macos/mkspecs/macx-clang/qmake.conf \
		../../6.4.0/macos/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../6.4.0/macos/mkspecs/features/exclusive_builds.prf \
		../../6.4.0/macos/mkspecs/features/mac/sdk.prf \
		../../6.4.0/macos/mkspecs/features/toolchain.prf \
		../../6.4.0/macos/mkspecs/features/mac/toolchain.prf \
		../../6.4.0/macos/mkspecs/features/default_pre.prf \
		../../6.4.0/macos/mkspecs/features/mac/default_pre.prf \
		../../6.4.0/macos/mkspecs/features/resolve_config.prf \
		../../6.4.0/macos/mkspecs/features/default_post.prf \
		../../6.4.0/macos/mkspecs/features/mac/default_post.prf \
		../../6.4.0/macos/mkspecs/features/mac/objective_c.prf \
		../../6.4.0/macos/mkspecs/features/resources_functions.prf \
		../../6.4.0/macos/mkspecs/features/qtquickcompiler.prf \
		../../6.4.0/macos/mkspecs/features/mac/mac.prf \
		../../6.4.0/macos/mkspecs/features/warn_on.prf \
		../../6.4.0/macos/mkspecs/features/qt.prf \
		../../6.4.0/macos/mkspecs/features/resources.prf \
		../../6.4.0/macos/mkspecs/features/moc.prf \
		../../6.4.0/macos/mkspecs/features/unix/opengl.prf \
		../../6.4.0/macos/mkspecs/features/uic.prf \
		../../6.4.0/macos/mkspecs/features/unix/thread.prf \
		../../6.4.0/macos/mkspecs/features/qmake_use.prf \
		../../6.4.0/macos/mkspecs/features/file_copies.prf \
		../../6.4.0/macos/mkspecs/features/mac/rez.prf \
		../../6.4.0/macos/mkspecs/features/mac/asset_catalogs.prf \
		../../6.4.0/macos/mkspecs/features/testcase_targets.prf \
		../../6.4.0/macos/mkspecs/features/exceptions.prf \
		../../6.4.0/macos/mkspecs/features/yacc.prf \
		../../6.4.0/macos/mkspecs/features/lex.prf \
		../test/test.pro \
		../../6.4.0/macos/lib/QtCharts.framework/Resources/QtCharts.prl \
		../../6.4.0/macos/lib/QtOpenGLWidgets.framework/Resources/QtOpenGLWidgets.prl \
		../../6.4.0/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		../../6.4.0/macos/lib/QtOpenGL.framework/Resources/QtOpenGL.prl \
		../../6.4.0/macos/lib/QtGui.framework/Resources/QtGui.prl \
		../../6.4.0/macos/lib/QtQml.framework/Resources/QtQml.prl \
		../../6.4.0/macos/lib/QtNetwork.framework/Resources/QtNetwork.prl \
		../../6.4.0/macos/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile ../test/test.pro -spec macx-clang CONFIG+=qtquickcompiler
../../6.4.0/macos/mkspecs/features/spec_pre.prf:
../../6.4.0/macos/mkspecs/features/device_config.prf:
../../6.4.0/macos/mkspecs/common/unix.conf:
../../6.4.0/macos/mkspecs/common/mac.conf:
../../6.4.0/macos/mkspecs/common/macx.conf:
../../6.4.0/macos/mkspecs/common/sanitize.conf:
../../6.4.0/macos/mkspecs/common/gcc-base.conf:
../../6.4.0/macos/mkspecs/common/gcc-base-mac.conf:
../../6.4.0/macos/mkspecs/common/clang.conf:
../../6.4.0/macos/mkspecs/common/clang-mac.conf:
../../6.4.0/macos/mkspecs/qconfig.pri:
../../6.4.0/macos/mkspecs/modules/qt_ext_freetype.pri:
../../6.4.0/macos/mkspecs/modules/qt_ext_libjpeg.pri:
../../6.4.0/macos/mkspecs/modules/qt_ext_libpng.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_charts.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_charts_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_chartsqml.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_chartsqml_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_concurrent.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_concurrent_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_core.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_core_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_dbus.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_dbus_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_designer.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_designer_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_fb_support_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_freetype_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_gui.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_gui_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_help.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_help_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_jpeg_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_labsanimation.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_labsanimation_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_labssettings.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_labssettings_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_labssharedimage.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_linguist.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_linguist_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_network.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_network_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_opengl.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_opengl_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_openglwidgets.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_png_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_printsupport.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_printsupport_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_qml.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_qml_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_qmlcore.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_qmlcore_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_qmldom_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_qmlintegration.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_qmlmodels.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_qmltest.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_qmltest_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_quick.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_quick_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_quickdialogs2.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_quicklayouts.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_quicktimeline.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_quickwidgets.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_remoteobjects.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_remoteobjectsqml.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_repparser.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_repparser_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_sql.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_sql_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_svg.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_svg_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_svgwidgets.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_testlib.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_testlib_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_tools_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_uiplugin.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_uitools.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_uitools_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_widgets.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_widgets_private.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_xml.pri:
../../6.4.0/macos/mkspecs/modules/qt_lib_xml_private.pri:
../../6.4.0/macos/mkspecs/features/qt_functions.prf:
../../6.4.0/macos/mkspecs/features/qt_config.prf:
../../6.4.0/macos/mkspecs/macx-clang/qmake.conf:
../../6.4.0/macos/mkspecs/features/spec_post.prf:
.qmake.stash:
../../6.4.0/macos/mkspecs/features/exclusive_builds.prf:
../../6.4.0/macos/mkspecs/features/mac/sdk.prf:
../../6.4.0/macos/mkspecs/features/toolchain.prf:
../../6.4.0/macos/mkspecs/features/mac/toolchain.prf:
../../6.4.0/macos/mkspecs/features/default_pre.prf:
../../6.4.0/macos/mkspecs/features/mac/default_pre.prf:
../../6.4.0/macos/mkspecs/features/resolve_config.prf:
../../6.4.0/macos/mkspecs/features/default_post.prf:
../../6.4.0/macos/mkspecs/features/mac/default_post.prf:
../../6.4.0/macos/mkspecs/features/mac/objective_c.prf:
../../6.4.0/macos/mkspecs/features/resources_functions.prf:
../../6.4.0/macos/mkspecs/features/qtquickcompiler.prf:
../../6.4.0/macos/mkspecs/features/mac/mac.prf:
../../6.4.0/macos/mkspecs/features/warn_on.prf:
../../6.4.0/macos/mkspecs/features/qt.prf:
../../6.4.0/macos/mkspecs/features/resources.prf:
../../6.4.0/macos/mkspecs/features/moc.prf:
../../6.4.0/macos/mkspecs/features/unix/opengl.prf:
../../6.4.0/macos/mkspecs/features/uic.prf:
../../6.4.0/macos/mkspecs/features/unix/thread.prf:
../../6.4.0/macos/mkspecs/features/qmake_use.prf:
../../6.4.0/macos/mkspecs/features/file_copies.prf:
../../6.4.0/macos/mkspecs/features/mac/rez.prf:
../../6.4.0/macos/mkspecs/features/mac/asset_catalogs.prf:
../../6.4.0/macos/mkspecs/features/testcase_targets.prf:
../../6.4.0/macos/mkspecs/features/exceptions.prf:
../../6.4.0/macos/mkspecs/features/yacc.prf:
../../6.4.0/macos/mkspecs/features/lex.prf:
../test/test.pro:
../../6.4.0/macos/lib/QtCharts.framework/Resources/QtCharts.prl:
../../6.4.0/macos/lib/QtOpenGLWidgets.framework/Resources/QtOpenGLWidgets.prl:
../../6.4.0/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl:
../../6.4.0/macos/lib/QtOpenGL.framework/Resources/QtOpenGL.prl:
../../6.4.0/macos/lib/QtGui.framework/Resources/QtGui.prl:
../../6.4.0/macos/lib/QtQml.framework/Resources/QtQml.prl:
../../6.4.0/macos/lib/QtNetwork.framework/Resources/QtNetwork.prl:
../../6.4.0/macos/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ../test/test.pro -spec macx-clang CONFIG+=qtquickcompiler

qmake_all: FORCE

test.app/Contents/PkgInfo: 
	@test -d test.app/Contents || mkdir -p test.app/Contents
	@$(DEL_FILE) test.app/Contents/PkgInfo
	@echo "APPL????" > test.app/Contents/PkgInfo
test.app/Contents/Resources/empty.lproj: 
	@test -d test.app/Contents/Resources || mkdir -p test.app/Contents/Resources
	@touch test.app/Contents/Resources/empty.lproj
	
test.app/Contents/Info.plist: 
	@test -d test.app/Contents || mkdir -p test.app/Contents
	@$(DEL_FILE) test.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,aleks.test,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},aleks.test,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.14,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,\$${IOS_LAUNCH_SCREEN},LaunchScreen,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,test,g" -e "s,@LIBRARY@,test,g" -e "s,\$${EXECUTABLE_NAME},test,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" ../../6.4.0/macos/mkspecs/macx-clang/Info.plist.app >test.app/Contents/Info.plist

all: Makefile \
		test.app/Contents/PkgInfo \
		test.app/Contents/Resources/empty.lproj \
		test.app/Contents/Info.plist test.app/Contents/MacOS/test

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../test/charts.h ../test/mainwindow.h ../test/parser.h $(DISTDIR)/
	$(COPY_FILE) --parents ../test/charts.cpp ../test/main.cpp ../test/mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../test/charts.ui ../test/mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r test.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=qtquickcompiler

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_qmlcache_make_all:
compiler_qmlcache_clean:
compiler_qmlcache_loader_make_all: qmlcache_loader.cpp
compiler_qmlcache_loader_clean:
	-$(DEL_FILE) qmlcache_loader.cpp
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_charts.cpp moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_charts.cpp moc_mainwindow.cpp
moc_charts.cpp: ../test/charts.h \
		../../6.4.0/macos/lib/QtWidgets.framework/Headers/QDialog \
		../../6.4.0/macos/lib/QtWidgets.framework/Headers/qdialog.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/QtCharts \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qchartglobal.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qabstractaxis.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qabstractbarseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qabstractseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qarealegendmarker.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qareaseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qbarcategoryaxis.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qbarlegendmarker.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qbarmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qbarseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qbarset.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qboxplotlegendmarker.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qboxplotmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qboxplotseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qboxset.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qcandlesticklegendmarker.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qcandlestickmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qcandlestickseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qcandlestickset.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qcategoryaxis.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qchart.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qchartview.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qcoloraxis.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qdatetimeaxis.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhbarmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhboxplotmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhcandlestickmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhorizontalbarseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhorizontalpercentbarseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhorizontalstackedbarseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhpiemodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhxymodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qlegend.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qlegendmarker.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qlineseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qlogvalueaxis.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qpercentbarseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qpielegendmarker.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qpiemodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qpieseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qpieslice.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qpolarchart.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qscatterseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qsplineseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qstackedbarseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qvalueaxis.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qvbarmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qvboxplotmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qvcandlestickmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qvpiemodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qvxymodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qxylegendmarker.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qxymodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qxyseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qtchartsversion.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/QLineSeries \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/QChartView \
		../../6.4.0/macos/lib/QtQml.framework/Headers/QJSEngine \
		../../6.4.0/macos/lib/QtQml.framework/Headers/qjsengine.h \
		../../6.4.0/macos/libexec/moc
	/Users/aleks/Qt/6.4.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=14 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/aleks/Qt/6.4.0/macos/mkspecs/macx-clang -I/Users/aleks/Qt/Project/test -I/Users/aleks/Qt/6.4.0/macos/lib/QtCharts.framework/Headers -I/Users/aleks/Qt/6.4.0/macos/lib/QtOpenGLWidgets.framework/Headers -I/Users/aleks/Qt/6.4.0/macos/lib/QtWidgets.framework/Headers -I/Users/aleks/Qt/6.4.0/macos/lib/QtOpenGL.framework/Headers -I/Users/aleks/Qt/6.4.0/macos/lib/QtGui.framework/Headers -I/Users/aleks/Qt/6.4.0/macos/lib/QtQml.framework/Headers -I/Users/aleks/Qt/6.4.0/macos/include -I/Users/aleks/Qt/6.4.0/macos/include/QtQmlIntegration -I/Users/aleks/Qt/6.4.0/macos/lib/QtNetwork.framework/Headers -I/Users/aleks/Qt/6.4.0/macos/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/aleks/Qt/6.4.0/macos/lib ../test/charts.h -o moc_charts.cpp

moc_mainwindow.cpp: ../test/mainwindow.h \
		../test/charts.h \
		../../6.4.0/macos/lib/QtWidgets.framework/Headers/QDialog \
		../../6.4.0/macos/lib/QtWidgets.framework/Headers/qdialog.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/QtCharts \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qchartglobal.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qabstractaxis.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qabstractbarseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qabstractseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qarealegendmarker.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qareaseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qbarcategoryaxis.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qbarlegendmarker.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qbarmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qbarseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qbarset.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qboxplotlegendmarker.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qboxplotmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qboxplotseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qboxset.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qcandlesticklegendmarker.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qcandlestickmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qcandlestickseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qcandlestickset.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qcategoryaxis.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qchart.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qchartview.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qcoloraxis.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qdatetimeaxis.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhbarmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhboxplotmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhcandlestickmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhorizontalbarseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhorizontalpercentbarseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhorizontalstackedbarseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhpiemodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhxymodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qlegend.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qlegendmarker.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qlineseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qlogvalueaxis.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qpercentbarseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qpielegendmarker.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qpiemodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qpieseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qpieslice.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qpolarchart.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qscatterseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qsplineseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qstackedbarseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qvalueaxis.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qvbarmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qvboxplotmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qvcandlestickmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qvpiemodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qvxymodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qxylegendmarker.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qxymodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qxyseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qtchartsversion.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/QLineSeries \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/QChartView \
		../../6.4.0/macos/lib/QtQml.framework/Headers/QJSEngine \
		../../6.4.0/macos/lib/QtQml.framework/Headers/qjsengine.h \
		../../6.4.0/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../6.4.0/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../6.4.0/macos/libexec/moc
	/Users/aleks/Qt/6.4.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=14 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/aleks/Qt/6.4.0/macos/mkspecs/macx-clang -I/Users/aleks/Qt/Project/test -I/Users/aleks/Qt/6.4.0/macos/lib/QtCharts.framework/Headers -I/Users/aleks/Qt/6.4.0/macos/lib/QtOpenGLWidgets.framework/Headers -I/Users/aleks/Qt/6.4.0/macos/lib/QtWidgets.framework/Headers -I/Users/aleks/Qt/6.4.0/macos/lib/QtOpenGL.framework/Headers -I/Users/aleks/Qt/6.4.0/macos/lib/QtGui.framework/Headers -I/Users/aleks/Qt/6.4.0/macos/lib/QtQml.framework/Headers -I/Users/aleks/Qt/6.4.0/macos/include -I/Users/aleks/Qt/6.4.0/macos/include/QtQmlIntegration -I/Users/aleks/Qt/6.4.0/macos/lib/QtNetwork.framework/Headers -I/Users/aleks/Qt/6.4.0/macos/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/aleks/Qt/6.4.0/macos/lib ../test/mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_charts.h ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_charts.h ui_mainwindow.h
ui_charts.h: ../test/charts.ui \
		../../6.4.0/macos/libexec/uic
	/Users/aleks/Qt/6.4.0/macos/libexec/uic ../test/charts.ui -o ui_charts.h

ui_mainwindow.h: ../test/mainwindow.ui \
		../../6.4.0/macos/libexec/uic
	/Users/aleks/Qt/6.4.0/macos/libexec/uic ../test/mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

charts.o: ../test/charts.cpp ../test/charts.h \
		../../6.4.0/macos/lib/QtWidgets.framework/Headers/QDialog \
		../../6.4.0/macos/lib/QtWidgets.framework/Headers/qdialog.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/QtCharts \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qchartglobal.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qabstractaxis.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qabstractbarseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qabstractseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qarealegendmarker.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qareaseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qbarcategoryaxis.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qbarlegendmarker.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qbarmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qbarseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qbarset.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qboxplotlegendmarker.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qboxplotmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qboxplotseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qboxset.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qcandlesticklegendmarker.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qcandlestickmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qcandlestickseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qcandlestickset.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qcategoryaxis.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qchart.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qchartview.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qcoloraxis.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qdatetimeaxis.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhbarmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhboxplotmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhcandlestickmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhorizontalbarseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhorizontalpercentbarseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhorizontalstackedbarseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhpiemodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhxymodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qlegend.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qlegendmarker.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qlineseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qlogvalueaxis.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qpercentbarseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qpielegendmarker.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qpiemodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qpieseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qpieslice.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qpolarchart.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qscatterseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qsplineseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qstackedbarseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qvalueaxis.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qvbarmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qvboxplotmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qvcandlestickmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qvpiemodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qvxymodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qxylegendmarker.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qxymodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qxyseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qtchartsversion.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/QLineSeries \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/QChartView \
		../../6.4.0/macos/lib/QtQml.framework/Headers/QJSEngine \
		../../6.4.0/macos/lib/QtQml.framework/Headers/qjsengine.h \
		ui_charts.h \
		../test/parser.h \
		../../6.4.0/macos/lib/QtWidgets.framework/Headers/QMessageBox \
		../../6.4.0/macos/lib/QtWidgets.framework/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o charts.o ../test/charts.cpp

main.o: ../test/main.cpp ../test/mainwindow.h \
		../test/charts.h \
		../../6.4.0/macos/lib/QtWidgets.framework/Headers/QDialog \
		../../6.4.0/macos/lib/QtWidgets.framework/Headers/qdialog.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/QtCharts \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qchartglobal.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qabstractaxis.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qabstractbarseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qabstractseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qarealegendmarker.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qareaseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qbarcategoryaxis.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qbarlegendmarker.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qbarmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qbarseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qbarset.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qboxplotlegendmarker.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qboxplotmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qboxplotseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qboxset.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qcandlesticklegendmarker.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qcandlestickmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qcandlestickseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qcandlestickset.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qcategoryaxis.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qchart.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qchartview.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qcoloraxis.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qdatetimeaxis.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhbarmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhboxplotmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhcandlestickmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhorizontalbarseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhorizontalpercentbarseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhorizontalstackedbarseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhpiemodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhxymodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qlegend.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qlegendmarker.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qlineseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qlogvalueaxis.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qpercentbarseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qpielegendmarker.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qpiemodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qpieseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qpieslice.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qpolarchart.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qscatterseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qsplineseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qstackedbarseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qvalueaxis.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qvbarmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qvboxplotmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qvcandlestickmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qvpiemodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qvxymodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qxylegendmarker.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qxymodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qxyseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qtchartsversion.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/QLineSeries \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/QChartView \
		../../6.4.0/macos/lib/QtQml.framework/Headers/QJSEngine \
		../../6.4.0/macos/lib/QtQml.framework/Headers/qjsengine.h \
		../../6.4.0/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../6.4.0/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../6.4.0/macos/lib/QtWidgets.framework/Headers/QApplication \
		../../6.4.0/macos/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../test/main.cpp

mainwindow.o: ../test/mainwindow.cpp ../test/mainwindow.h \
		../test/charts.h \
		../../6.4.0/macos/lib/QtWidgets.framework/Headers/QDialog \
		../../6.4.0/macos/lib/QtWidgets.framework/Headers/qdialog.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/QtCharts \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qchartglobal.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qabstractaxis.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qabstractbarseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qabstractseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qarealegendmarker.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qareaseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qbarcategoryaxis.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qbarlegendmarker.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qbarmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qbarseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qbarset.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qboxplotlegendmarker.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qboxplotmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qboxplotseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qboxset.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qcandlesticklegendmarker.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qcandlestickmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qcandlestickseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qcandlestickset.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qcategoryaxis.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qchart.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qchartview.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qcoloraxis.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qdatetimeaxis.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhbarmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhboxplotmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhcandlestickmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhorizontalbarseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhorizontalpercentbarseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhorizontalstackedbarseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhpiemodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qhxymodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qlegend.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qlegendmarker.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qlineseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qlogvalueaxis.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qpercentbarseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qpielegendmarker.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qpiemodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qpieseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qpieslice.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qpolarchart.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qscatterseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qsplineseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qstackedbarseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qvalueaxis.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qvbarmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qvboxplotmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qvcandlestickmodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qvpiemodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qvxymodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qxylegendmarker.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qxymodelmapper.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qxyseries.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/qtchartsversion.h \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/QLineSeries \
		../../6.4.0/macos/lib/QtCharts.framework/Headers/QChartView \
		../../6.4.0/macos/lib/QtQml.framework/Headers/QJSEngine \
		../../6.4.0/macos/lib/QtQml.framework/Headers/qjsengine.h \
		../../6.4.0/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../6.4.0/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ../test/mainwindow.cpp

moc_charts.o: moc_charts.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_charts.o moc_charts.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/test/bin || mkdir -p $(INSTALL_ROOT)/opt/test/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/test/bin/test.app
	
	$(QINSTALL) test.app $(INSTALL_ROOT)/opt/test/bin/test.app
	-$(STRIP) $(INSTALL_ROOT)/opt/test/bin/test.app/Contents/MacOS/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/test/bin/test.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/test/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

.SUFFIXES:

